CREATE TABLE TB_ECOMMERCE(
ID BIGINT AUTO_INCREMENT,
NOMEDOPRODUTO VARCHAR(255),
MARCA VARCHAR(255),
TAMANHO CHAR,
PRECO DECIMAL,
COR VARCHAR(255),
PRIMARY KEY (ID)
);

SELECT * FROM TB_ECOMMERCE;

INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('REGATA', 'JUJU', 'G', '200.00', 'PRETA');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('VESTIDO', 'JUJU', 'G', '200.00', 'AZUL');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('CAMISETA GOLA V', 'LILI', 'G', '400.00', 'CINZA');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('CAMISA', 'LILI', 'M', '350.00', 'BRANCA');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('SHORT', 'CELI', 'M', '400.00', 'ROXO');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('CALÇA', 'CELI', 'P', '450.00', 'AMARELA');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('CAMISETA POLO', 'FAFA', 'P', '500.00', 'ROSA');
INSERT INTO TB_ECOMMERCE (NOMEDOPRODUTO, MARCA, TAMANHO, PRECO, COR) VALUES ('BLUSÃO', 'FAFA', 'M', '600.00', 'VERDE');

SELECT * FROM TB_ECOMMERCE WHERE PRECO > 500;
SELECT * FROM TB_ECOMMERCE WHERE PRECO < 500;

UPDATE TB_ECOMMERCE SET TAMANHO = 'P' WHERE ID = 1;




