CREATE DATABASE DB_NEW_SERVICO_RH;

USE DB_NEW_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME varchar(255),
IDADE INT,
CARGO VARCHAR(255),
DEPARTAMENTO VARCHAR(255),
SALARIO DECIMAL,
PRIMARY KEY(ID)
);
SELECT * FROM TB_FUNCIONARIOS;

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('AMANDA','35','RECEPCIONISTA','ATENDIMENTO AO CLIENTE','1600.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('LAURA','28','GERENTE','ADMINISTRAÇÃO','2500.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('RAFAEL','41','DESENVOLVEDOR','TI','6000.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('JULIA','21','AUXILIAR DE LIMPEZA','ADMINISTRAÇÃO','1089.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('LEONARDO','50','PRESIDENTE','PRESIDÊNCIA','40000.00');

SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO > 2000;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO < 2000;
UPDATE TB_FUNCIONARIOS SET IDADE = '29' WHERE ID = 2;