SELECT * FROM TB_FUNCIONARIOS;

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('AMANDA','35','RECEPCIONISTA','ATENDIMENTO AO CLIENTE','1600.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('LAURA','28','GERENTE','ADMINISTRAÇÃO','2500.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('RAFAEL','41','DESENVOLVEDOR','TI','6000.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('JULIA','21','AUXILIAR DE LIMPEZA','ADMINISTRAÇÃO','1089.00');
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, CARGO, DEPARTAMENTO, SALARIO) VALUES ('LEONARDO','50','PRESIDENTE','PRESIDÊNCIA','40000.00');