CREATE TABLE TB_REGISTRO_ESCOLAR(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
IDADE INT,
SERIE VARCHAR(255),
GENERO CHAR(255),
NOTA DECIMAL,
PRIMARY KEY(ID)
);

SELECT * FROM TB_REGISTRO_ESCOLAR;

INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('ANA', '14', '8 ANO B', 'F', '6.5');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('MARIA', '18', '3 ANO B', 'F', '8.0');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('PABLLO', '17', '3 ANO B', 'M', '9.0');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('CARLOS', '15', '1 ANO B', 'M', '10.0');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('LUCIA', '12', '7 ANO B', 'F', '4.5');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('JULIO', '13', '8 ANO B', 'M', '3.5');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('EDUARDA', '11', '5 ANO B', 'F', '7.0');
INSERT INTO TB_REGISTRO_ESCOLAR (NOME, IDADE, SERIE, GENERO, NOTA) VALUES ('BEN', '10', '4 ANO B', 'O', '8.0');

SELECT * FROM TB_REGISTRO_ESCOLAR WHERE NOTA > 7;
SELECT * FROM TB_REGISTRO_ESCOLAR WHERE NOTA < 7;

UPDATE TB_REGISTRO_ESCOLAR SET IDADE = '18' WHERE ID = 3;


