CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
COSMETICOS VARCHAR(255),
MEDICAMENTOS VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
PERFUME VARCHAR(255),
COMPRIMIDO VARCHAR(255),
CREME VARCHAR(255),
VALOR INT,
PRIMARY KEY(ID),
PRODUTOS_ID BIGINT,
FOREIGN KEY (PRODUTOS_ID) REFERENCES TB_PRODUTOS(ID)
);

SELECT * FROM TB_CATEGORIAS;

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS (COSMETICOS, MEDICAMENTOS) VALUES ('FEMININOS', 'PARA DOR NO PESCOÇO');
INSERT INTO TB_CATEGORIAS (COSMETICOS, MEDICAMENTOS) VALUES ('MASCULINOS', 'PARA DOR DE CABEÇA');
INSERT INTO TB_CATEGORIAS (COSMETICOS, MEDICAMENTOS) VALUES ('INFANTIL', 'PARA DOR NO OMBRO');
INSERT INTO TB_CATEGORIAS (COSMETICOS, MEDICAMENTOS) VALUES ('FEMININO', 'PARA DOR NA COXA');
INSERT INTO TB_CATEGORIAS (COSMETICOS, MEDICAMENTOS) VALUES ('INFANTIL', 'PARA DOR NO PÉ');


INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('DOCE', 'SIM', 'HIDRATANTE', '70.00', '1');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('FLORAL', 'SIM', 'PELE MISTA', '7.00', '2');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('FLORAL', 'NÃO', 'PELE OLEOSA', '90.00', '3');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('CÍTRICO', 'NÃO', 'HIDRATANTE', '20.00', '4');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('DOCE', 'SIM',  'PELE MISTA', '50.00', '5');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('FLORAL', 'NÃO', 'PELE SECA', '60.00', '1');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('DOCE', 'SIM', 'PELE OLEOSA' ,'30.00', '2');
INSERT INTO TB_PRODUTOS (PERFUME, COMPRIMIDO, CREME, VALOR, PRODUTOS_ID) VALUES ('FLORAL', 'NÃO', 'PELE NORMAL', '40.00', '3');

SELECT * FROM TB_PRODUTOS WHERE VALOR > 50.00;

SELECT * FROM TB_PRODUTOS WHERE VALOR >= 5.00 AND VALOR <= 60.00;

SELECT * FROM TB_PRODUTOS WHERE CREME LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.PRODUTOS_ID;

SELECT TB_PRODUTOS.PERFUME, TB_CATEGORIAS.COSMETICOS, TB_CATEGORIAS.MEDICAMENTOS FROM TB_PRODUTOS INNER JOIN
TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.PRODUTOS_ID WHERE TB_CATEGORIAS.COSMETICOS = 'FEMININOS';


