CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSE(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
ARMA VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PERSONAGEM(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255),
ATAQUE DOUBLE,
DEFESA DOUBLE,
HP INT,
PRIMARY KEY(ID),
CLASSE_ID BIGINT,
FOREIGN KEY (CLASSE_ID) REFERENCES TB_CLASSE(ID)
);

SELECT * FROM TB_CLASSE;
SELECT * FROM TB_PERSONAGEM;

INSERT INTO TB_CLASSE (NOME, ARMA) VALUES ('LADRÃO','REVÓLVER');
INSERT INTO TB_CLASSE (NOME, ARMA) VALUES('BRUXA','VARINHA');
INSERT INTO TB_CLASSE (NOME, ARMA) VALUES ('GUERREIRO','ESPADA');
INSERT INTO TB_CLASSE (NOME, ARMA) VALUES ('MAGO','CAJADO');
INSERT INTO TB_CLASSE (NOME, ARMA) VALUES ('CAÇADOR','MACHADO');

INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('SAMY', '3000', '2300', '1000', 1);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('MALU', '2200', '1000', '1000', 2);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('LEO', '5000', '1000', '1000', 3);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('JORGE', '3000', '2100', '1000', 4);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('CARLA', '2000', '4000', '1000', 5);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('LUISA', '4000', '5000', '1000', 3);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('JOÃO', '1000', '2300', '1000', 2);
INSERT INTO TB_PERSONAGEM (NOME, ATAQUE, DEFESA, HP, CLASSE_ID) VALUES ('PEDRO', '5000', '2000', '1000', 4);

SELECT * FROM TB_PERSONAGEM WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGEM WHERE DEFESA >= 1000 AND DEFESA <= 2000;

SELECT * FROM TB_PERSONAGEM WHERE NOME LIKE "%C%";

SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSE ON TB_CLASSE.ID = TB_PERSONAGEM.CLASSE_ID;

SELECT TB_PERSONAGEM.NOME, TB_CLASSE.NOME, TB_CLASSE.ARMA FROM TB_PERSONAGEM INNER JOIN
TB_CLASSE ON TB_CLASSE.ID = TB_PERSONAGEM.CLASSE_ID WHERE TB_CLASSE.NOME = 'BRUXA';







