CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TAMANHO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
DOCEOUSALGADA VARCHAR(255),
SABOR VARCHAR(255),
BORDA VARCHAR(255),
PRECO DOUBLE,
PRIMARY KEY(ID),
TIPOS_ID BIGINT,
FOREIGN KEY (TIPOS_ID) REFERENCES TB_CATEGORIAS(ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS (TAMANHO, QUANTIDADE) VALUES ('GRANDE', '2');
INSERT INTO TB_CATEGORIAS (TAMANHO, QUANTIDADE) VALUES ('BROTO', '3');
INSERT INTO TB_CATEGORIAS (TAMANHO, QUANTIDADE) VALUES ('GRANDE', '1');
INSERT INTO TB_CATEGORIAS (TAMANHO, QUANTIDADE) VALUES ('GRANDE', '4');
INSERT INTO TB_CATEGORIAS (TAMANHO, QUANTIDADE) VALUES ('BROTO', '1');

INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('DOCE', 'BANANA COM NUTELLA', 'SEM BORDA', '50.00', '3');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('SALGADA', 'MUSSARELA', 'COM BORDA', '25.00', '4');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('DOCE', 'BRIGADEIRO','SEM BORDA', '70.00', '2');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('SALGADA', 'JARDINEIRA', 'SEM BORDA', '40.00', '1');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('DOCE', 'AÇAÍ', 'SEM BORDA', '60.00', '1');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('SALGADA', 'CALABRESA', 'COM BORDA', '20.00', '2');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('DOCE', 'CHOCOLATE COM MORANGO', 'SEM BORDA', '80.00', '4');
INSERT INTO TB_PIZZAS (DOCEOUSALGADA, SABOR, BORDA, PRECO, TIPOS_ID) VALUES ('SALGADA', 'MARGUERITA',  'COM BORDA', '30.00', '3');

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;

SELECT * FROM TB_PIZZAS WHERE PRECO >= 50.00 AND PRECO <= 100.00;

SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.TIPOS_ID;

SELECT TB_PIZZAS.SABOR, TB_CATEGORIAS.TAMANHO, TB_CATEGORIAS.QUANTIDADE FROM TB_PIZZAS INNER JOIN
TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.TIPOS_ID WHERE TB_CATEGORIAS.TAMANHO = 'GRANDE';











